# Generated by Django 4.0.4 on 2022-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_register_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
