# Generated by Django 4.0.4 on 2022-05-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_register_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='accounts',
        ),
    ]
