# Generated by Django 4.0.3 on 2022-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_adminsignin_officesignin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='address',
            field=models.CharField(default='default: India, You can update this field in edit Profile', max_length=100),
        ),
    ]
