# Generated by Django 4.0.3 on 2022-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_signin_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('farmAddress', models.CharField(max_length=100)),
                ('farmRegNo', models.IntegerField()),
                ('certificate', models.FileField(upload_to='')),
            ],
        ),
    ]
