# Generated by Django 4.0.3 on 2022-08-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
